version: 2
jobs:
  build:
    working_directory: "~"
    docker:
      - image: "debian:jessie"
    steps:
      - run: echo "A first hello" 
  build-more-things:
    working_directory: "~"
    docker:
      - image: "debian:jessie"
    steps:
      - run: echo "And a more familiar hi"
