version: 2
jobs:
  one:
    working_directory: "~"
    docker:
      - image: "debian:jessie"
    steps:
      - run: A first hello 
  two:
    working_directory: "~"
    docker:
      - image: "debian:jessie"
    steps:
      - run: And a more familiar hi
