version: 2
jobs:
  one:
    working_directory: "~"
    docker:
      - image: "debian:jessie"
    steps:
      - run: echo "A first hello" 
  two:
    working_directory: "~"
    docker:
      - image: "debian:jessie"
    steps:
      - run: echo "And a more familiar hi"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
